export const PLAYER_COLORS = [
  { name: 'NAVY', code: '#001f3f'},
  { name: 'BLUE', code: '#0074D9'},
  { name: 'AQUA', code: '#7FDBFF'},
  { name: 'TEAL', code: '#39CCCC'},
  { name: 'OLIVE', code: '#3D9970'},
  { name: 'GREEN', code: '#2ECC40'},
  { name: 'LIME', code: '#01FF70'},
  { name: 'YELLOW', code: '#FFDC00'},
  { name: 'ORANGE', code: '#FF851B'},
  { name: 'RED', code: '#FF4136'},
  { name: 'MAROON', code: '#85144b'},
  { name: 'FUCHSIA', code: '#F012BE'},
  { name: 'PURPLE', code: '#B10DC9'},
  { name: 'BLACK', code: '#111111'},
  { name: 'GRAY', code: '#AAAAAA'},
  { name: 'SILVER', code: '#DDDDDD'},
];
// {
//   NAVY = '#001f3f',
//   BLUE = '#0074D9',
//   AQUA = '#7FDBFF',
//   TEAL = '#39CCCC',
//   OLIVE = '#3D9970',
//   GREEN = '#2ECC40',
//   LIME = '#01FF70',
//   YELLOW = '#FFDC00',
//   ORANGE = '#FF851B',
//   RED = '#FF4136',
//   MAROON = '#85144b',
//   FUCHSIA = '#F012BE',
//   PURPLE = '#B10DC9',
//   BLACK = '#111111',
//   GRAY = '#AAAAAA',
//   SILVER = '#DDDDDD',
// }
